# Generated by Django 4.0 on 2021-12-27 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audiences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.PositiveIntegerField(null=True, unique=True, verbose_name='Telegram ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Название')),
                ('category', models.CharField(max_length=100, null=True, verbose_name='Категория')),
                ('list', models.CharField(max_length=9999, verbose_name='Список пользователей')),
            ],
            options={
                'verbose_name': 'Аудитория',
                'verbose_name_plural': 'Аудитории',
            },
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Название товара')),
                ('price', models.CharField(max_length=100, null=True, verbose_name='Цена товара (в копейках, не меньше 10000)')),
                ('description', models.CharField(max_length=100, null=True, verbose_name='Описание товара')),
                ('volume', models.CharField(max_length=100, null=True, verbose_name='Кол-во сообщений')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата и время транзакци (UTC)')),
                ('external_id', models.PositiveIntegerField(null=True, unique=True, verbose_name='Telegram ID')),
                ('summ', models.CharField(max_length=100, null=True, verbose_name='Сумма')),
                ('comment', models.CharField(max_length=100, null=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Транзакция',
                'verbose_name_plural': 'Транзакции',
            },
        ),
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.PositiveIntegerField(null=True, unique=True, verbose_name='Telegram ID')),
                ('ref_count', models.CharField(max_length=100, null=True, verbose_name='Рефералы')),
                ('sub_ref_count', models.CharField(max_length=100, null=True, verbose_name='Суб-рефералы')),
                ('items_count', models.CharField(max_length=100, null=True, verbose_name='Сообщения')),
                ('wallet', models.CharField(max_length=100, null=True, verbose_name='Кошелёк')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
        migrations.CreateModel(
            name='ReferalBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.PositiveIntegerField(null=True, unique=True, verbose_name='Telegram ID')),
                ('from_who', models.CharField(max_length=100, null=True, verbose_name='Кто пригласил')),
                ('referals', models.CharField(max_length=9999, verbose_name='Рефералы')),
            ],
            options={
                'verbose_name': 'Рферал',
                'verbose_name_plural': 'Рефералы',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата и время регистрации (UTC)')),
                ('external_id', models.PositiveIntegerField(null=True, unique=True, verbose_name='Telegram ID')),
                ('username', models.CharField(max_length=30, null=True, verbose_name='Ник')),
                ('firstname', models.CharField(max_length=30, null=True, verbose_name='Имя')),
                ('lastname', models.CharField(max_length=30, null=True, verbose_name='Фамилия')),
                ('phone_number', models.CharField(max_length=30, null=True, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Аккаунт',
                'verbose_name_plural': 'Аккаунты',
            },
        ),
    ]
