# Generated by Django 4.0 on 2021-12-27 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='items_count',
            field=models.CharField(default=0, max_length=100, verbose_name='Сообщения'),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='ref_count',
            field=models.CharField(default=0, max_length=100, verbose_name='Рефералы'),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='sub_ref_count',
            field=models.CharField(default=0, max_length=100, verbose_name='Суб-рефералы'),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='wallet',
            field=models.CharField(default=0, max_length=100, verbose_name='Кошелёк'),
        ),
    ]
