# Generated by Django 4.0 on 2021-12-28 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0003_alter_items_price_alter_items_volume_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiences',
            name='list',
        ),
        migrations.AddField(
            model_name='audiences',
            name='username',
            field=models.CharField(max_length=100, null=True, verbose_name='Ник клиента'),
        ),
        migrations.AlterField(
            model_name='audiences',
            name='category',
            field=models.CharField(max_length=100, null=True, verbose_name='Категория базы'),
        ),
        migrations.AlterField(
            model_name='audiences',
            name='external_id',
            field=models.PositiveIntegerField(null=True, unique=True, verbose_name='Telegram ID владельца базы'),
        ),
        migrations.AlterField(
            model_name='audiences',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='Название базы'),
        ),
        migrations.AlterField(
            model_name='items',
            name='price',
            field=models.PositiveBigIntegerField(null=True, verbose_name='Цена товара (в копейках, не меньше 10000)'),
        ),
        migrations.AlterField(
            model_name='items',
            name='volume',
            field=models.PositiveBigIntegerField(null=True, verbose_name='Кол-во сообщений'),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='summ',
            field=models.PositiveBigIntegerField(null=True, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='items_count',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Сообщения'),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='ref_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Рефералы'),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='sub_ref_count',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Суб-рефералы'),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='wallet',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Кошелёк'),
        ),
        migrations.AlterField(
            model_name='referalbase',
            name='from_who',
            field=models.PositiveIntegerField(null=True, verbose_name='Кто пригласил'),
        ),
    ]
