# Generated by Django 4.0 on 2021-12-29 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0004_remove_audiences_list_audiences_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiences',
            name='time',
            field=models.DateTimeField(null=True, verbose_name='Дата и время последнего сообщения (UTC)'),
        ),
    ]
