# Generated by Django 4.0 on 2021-12-29 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0005_audiences_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenthistory',
            name='external_id',
            field=models.PositiveIntegerField(null=True, verbose_name='Telegram ID'),
        ),
    ]
