# Generated by Django 3.2.6 on 2022-02-22 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0006_alter_paymenthistory_external_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymenthistory',
            options={'verbose_name': 'Оплата', 'verbose_name_plural': 'Оплаты'},
        ),
        migrations.AlterModelOptions(
            name='profiles',
            options={'verbose_name': 'Профиль клиента', 'verbose_name_plural': 'Профили клиентов'},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'Регистрация', 'verbose_name_plural': 'Регистрации'},
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата и время транзакции (UTC)'),
        ),
    ]
