# Generated by Django 3.2.6 on 2022-02-23 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0007_auto_20220222_1907'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.PositiveIntegerField(null=True, unique=True, verbose_name='Telegram ID владельца')),
                ('chat', models.CharField(max_length=512, null=True, verbose_name='Название чата')),
            ],
            options={
                'verbose_name': 'Чат база',
                'verbose_name_plural': 'База чатов',
            },
        ),
        migrations.DeleteModel(
            name='Audiences',
        ),
        migrations.AlterModelOptions(
            name='paymenthistory',
            options={'verbose_name': 'Транзакция', 'verbose_name_plural': 'Транзакции'},
        ),
        migrations.AlterModelOptions(
            name='profiles',
            options={'verbose_name': 'Профиль юзера', 'verbose_name_plural': 'Профили юзеров'},
        ),
        migrations.AlterModelOptions(
            name='referalbase',
            options={'verbose_name': 'Рферал база', 'verbose_name_plural': 'База рефералов'},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'Юзер', 'verbose_name_plural': 'Юзеры'},
        ),
        migrations.RemoveField(
            model_name='items',
            name='volume',
        ),
        migrations.RemoveField(
            model_name='profiles',
            name='items_count',
        ),
        migrations.RemoveField(
            model_name='users',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='users',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='users',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='items',
            name='active_time',
            field=models.DateTimeField(null=True, verbose_name='Срок действия'),
        ),
        migrations.AddField(
            model_name='items',
            name='cells',
            field=models.PositiveBigIntegerField(null=True, verbose_name='Кол-во ячеек'),
        ),
        migrations.AddField(
            model_name='profiles',
            name='cells_count',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Кол-во ячеек (всего)'),
        ),
        migrations.AddField(
            model_name='profiles',
            name='cells_occupied',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Занято ячеек'),
        ),
        migrations.AddField(
            model_name='profiles',
            name='team_occupied',
            field=models.PositiveBigIntegerField(default=1, verbose_name='Размер комманды'),
        ),
        migrations.AddField(
            model_name='profiles',
            name='team_volume',
            field=models.PositiveBigIntegerField(default=1, verbose_name='Размер комманды (всего)'),
        ),
        migrations.AlterField(
            model_name='items',
            name='description',
            field=models.CharField(max_length=100, null=True, verbose_name='Описание пакета'),
        ),
        migrations.AlterField(
            model_name='items',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='Название пакета'),
        ),
        migrations.AlterField(
            model_name='items',
            name='price',
            field=models.PositiveBigIntegerField(null=True, verbose_name='Цена пакета (в копейках, не меньше 10000)'),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='wallet',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Кошелёк Голды'),
        ),
        migrations.AddField(
            model_name='profiles',
            name='chats',
            field=models.ManyToManyField(to='tg.ChatBase'),
        ),
    ]
